export const fieldLabels: Record<string, string> = {
  formattedDate: "Datum",
  salutation: "Anrede",
  firstName: "Vorname",
  lastName: "Nachname",
  companyName: "Firmenname",
  quantity: "Anzahl",
  pid: "Produkt ID",
  email: "E-Mail",
  phone: "Telefon",
  status: "Status",
  paid: "Bezahlt",
  street: "Straße",
  postcode: "Postleitzahl",
  city: "Stadt",
  country: "Land",
  deliveryOption: "Versandart",
  deliverySalutation: "Liefer-Anrede",
  deliveryFirstName: "Liefer-Vorname",
  deliveryLastName: "Liefer-Nachname",
  deliveryStreet: "Liefer-Straße",
  deliveryPostcode: "Liefer-Postleitzahl",
  deliveryCity: "Liefer-Stadt",
  deliveryCountry: "Liefer-Land",
  comment: "Kommentar",
};